### ISSUE TITLE
waning

### ISSUE THREAD

**Issue by kazu-yamamoto** [Certerazvi/h2specd#4]
If we forget to use `sudo`, h2specd cannot open port 443 but does not display any warnings. It should warn loudly if bad things happen.

**Comment by kazu-yamamoto** [comment]
Did you take care of this? I have no warnings when I ommit `sudo`.

**Comment by Certerazvi** [comment]
Not yet. I'm working on it.

**Comment by Certerazvi** [comment]
Solved! Just pushed the changes and will make a new release soon with this. Thank you!
